name: speech_delay
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  carousel_slider: 4.0.0
  cloud_firestore: 3.1.10
  cupertino_icons: ^1.0.2
  dropdown_search: ^2.0.1
  get: 4.6.1
  google_fonts: 2.3.1
  intl: ^0.17.0
  firebase_core: 1.13.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

